### PR TITLE
Used database,  modified orders table 

### PR DESCRIPTION
**Pull request by Ararsa-Derese**

### CODE REVIEW

**Comment by BisRyy** [comment]
Looks good, what happened to the buttons?

**Comment by Ararsa-Derese** [comment]
They work fine on me what's wrong ?

**Comment by BisRyy** [comment]
Ohh, buttons only on Waiting. Nice. :+1: 

Make sure it works with the updated database. I changed some things to make it work but needs some fix.
Check that and add a shipment feature that ships different orders to one container.

**Comment by BisRyy** [comment]
Also try forking again. the previous commits are making it hard to see the new ones.

**Comment by Ararsa-Derese** [comment]
Okay

**Pull request closed without merging**
